In [1]:
import torch
from icecream import ic

ic(torch.__version__)

ic| torch.__version__: '2.3.1'


'2.3.1'

In [2]:
idx = torch.tensor([2, 3, 1])
num_idx = max(idx) + 1
out_dim = 5

In [3]:
torch.manual_seed(39)
embedding = torch.nn.Embedding(num_idx, out_dim)
embedding.weight

Parameter containing:
tensor([[ 0.0648, -0.7227, -0.7643,  0.9232, -1.4324],
        [ 0.9932,  0.0806, -1.2377,  0.1923,  0.1334],
        [-0.5778, -0.0934,  0.9363, -0.7128,  1.7307],
        [ 0.9606, -1.0155,  0.7749, -0.3227, -1.3694]], requires_grad=True)

In [4]:
embedding(torch.tensor([1]))

tensor([[ 0.9932,  0.0806, -1.2377,  0.1923,  0.1334]],
       grad_fn=<EmbeddingBackward0>)

In [5]:
embedding(idx)

tensor([[-0.5778, -0.0934,  0.9363, -0.7128,  1.7307],
        [ 0.9606, -1.0155,  0.7749, -0.3227, -1.3694],
        [ 0.9932,  0.0806, -1.2377,  0.1923,  0.1334]],
       grad_fn=<EmbeddingBackward0>)

In [6]:
onehot = torch.nn.functional.one_hot(idx)
ic(onehot)

ic| onehot: tensor([[0, 0, 1, 0],
                    [0, 0, 0, 1],
                    [0, 1, 0, 0]])


tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

In [7]:
torch.manual_seed(39)
linear = torch.nn.Linear(num_idx, out_dim, bias=False)
linear.weight

Parameter containing:
tensor([[-0.4964, -0.0493, -0.2379, -0.1464],
        [-0.4771,  0.4237, -0.2552, -0.3650],
        [-0.3875, -0.1352,  0.0317,  0.4756],
        [ 0.2606, -0.1501,  0.1901, -0.3666],
        [ 0.4745, -0.1614,  0.4700,  0.2483]], requires_grad=True)

In [8]:
linear.weight = torch.nn.Parameter(embedding.weight.T)

In [9]:
linear(onehot.float())

tensor([[-0.5778, -0.0934,  0.9363, -0.7128,  1.7307],
        [ 0.9606, -1.0155,  0.7749, -0.3227, -1.3694],
        [ 0.9932,  0.0806, -1.2377,  0.1923,  0.1334]], grad_fn=<MmBackward0>)

In [10]:
embedding(idx)

tensor([[-0.5778, -0.0934,  0.9363, -0.7128,  1.7307],
        [ 0.9606, -1.0155,  0.7749, -0.3227, -1.3694],
        [ 0.9932,  0.0806, -1.2377,  0.1923,  0.1334]],
       grad_fn=<EmbeddingBackward0>)